### ISSUE TITLE
Design Card components (m1)

### ISSUE THREAD

**Issue by RudeSoul** [itsnporg/blog-itsnp-frontend#3]
### Requirements
1. The cards need to be pixel perfect to the Figma design,
2. Card must be responsive for all screen
3. props should be maintained if needed

### TODO : cards

- [x] 1) Design postsTrendingComponent card, Here is figma link : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=44%3A88

- [x] 2) Design blog post card component, Here is Figma link: https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=323%3A216

- [x] 3) Design Small card blog post , Here is Figma link : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A390

- [x] 4) Design Post medium blog post card Here is figma link : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A398

- [x] 5) Design Joinmadhyam Card Here is figma link : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A405
