### ISSUE TITLE
Design Navbar and components (m2)

### ISSUE THREAD

**Issue by questbibek** [itsnporg/blog-itsnp-frontend#4]
### Requirements
1. The cards need to be pixel perfect to the Figma design,
2. Card must be responsive for all screen
3. props should be maintained if needed

### TODO : Navbar components

- [ ] 1) Design Navigation bar (Not logged in ), this is a nav menu, a user sees this if he/she is not logged, link to figma 
https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A426

- [ ] 2) Design Navigation bar ( logged in ), this is a nav menu, a user sees this if he/she is logged in to madhyam, link to figma 
https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A438

- [ ] 3) Design Navigation bar popup components , this is a nav notification menu, a user sees this if he/she is logged in to madhyam, link to figma 
https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A678

- [ ] 4) Design Navigation bar popup components , this is a nav profile menu, a user sees this if he/she is logged in to madhyam, link to figma https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A726
