### ISSUE TITLE
Design input components .(m3 )

### ISSUE THREAD

**Issue by questbibek** [itsnporg/blog-itsnp-frontend#5]
### Requirements
1. The cards need to be pixel perfect to the Figma design,
2. Card must be responsive for all screen
3. props should be maintained if needed

### TODO : components

- [ ] 1) Design newsletter input component , link to figma 
https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A488

- [ ] 2) Design join news letter link to figma : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=484%3A195

- [ ] 3) Design join news letter link to figma : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=484%3A195

- [ ] 4) Design input label (passive and active state ) link to figma design  : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=484%3A196

- [ ] 5) Design search input label link to figma design  :  https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=484%3A195

- [ ] 6) Design Design badge|Label components figma design  : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=484%3A197

- [ ] 7) Design category components figma design  : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=484%3A197
