### ISSUE TITLE
Design profile components (m4)

### ISSUE THREAD

**Issue by questbibek** [itsnporg/blog-itsnp-frontend#6]
### Requirements
1. The design need to be pixel perfect to the Figma design,
2. Design must be responsive for all screen
3. props should be maintained if needed

### TODO : Profile components

- [x] 1) Design Profile Author_1 ( at the end of the blog ) here is  https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A528

- [x] 2) Design Profile Author_2 (Top of the blog post ) Here is a figma link https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A533

- [x] 3) Design Follow profile (Righ side of the blog ) Here is a figma link 
https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A540

- [x] 4) Design Avatar (general avatar ) Here is a figma link : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=488%3A196

- [x] 5) Design Comment component. Here is the [Figma link](https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A580).
