### ISSUE TITLE
Design Button components (m5)

### ISSUE THREAD

**Issue by questbibek** [itsnporg/blog-itsnp-frontend#7]
### Requirements
1. The Buttons need to be pixel perfect to the Figma design,
2. Buttons must be responsive for all screen
3. props should be maintained if needed

### TODO : Buttons

- [ ] 1) Design Primary buttons it has two state Active and passive for now, here is a figma link : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=489%3A3

- [ ] 2) Design Get started buttons https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=489%3A4

- [ ] 3) Design Follow / Following buttons https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=489%3A2

- [ ] 4) Design Follow with followers count button  https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A811

- [ ] 5) Design Subscribe newsletter button here is a figma link : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=489%3A5

- [ ] 6) Design Add button , Here is a figma link : https://www.figma.com/file/y9aknqd9ijJnyBF67fS6mF/UI-UX-For-temp-madhyam?node-id=443%3A818
